name: DiscordConnection
version: '${project.version}'
main: com.coin.discordconnection.DiscordConnection
api-version: 1.18
authors: [ Ryan_Tang ]
description: A Spigot plugin that connect discord bot with minecraft
commands:
  discord:
    description: discord
    usage: /<command>
  reply:
    description: reply to message
    usage: /<command> <messageid> <content>

#  discord token:
#    description: set the bot's token
#    usage: /<command> <token>
#  discord channel:
#    description: set the channel id
#    usage: /<command> <channelId>
#  discord activitytext:
#    description: set the activity text
#    usage: /<command> <text>