name: DiscordConnection
version: '${project.version}'
main: com.coin.discordconnection.DiscordConnection
api-version: 1.13
authors: [ Ryan_Tang ]
description: A Spigot plugin that connect discord bot with minecraft
commands:
  discord:
    description: discord
    usage: /<command>
  reply:
    description: reply to message
    usage: /<command> <messageid> <content>